sudo: false

cache:
  directories:
    - tests/elm-stuff/build-artifacts
    - sysconfcpus

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi


install:
  - npm install -g elm-test elm-format
  - wget https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz -O $(npm config get prefix)/bin/elm.gz
  - gunzip $(npm config get prefix)/bin/elm.gz
  - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 1"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 1 elm-old "$@"' > $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm-old
  - cd tests
  - npm install
  - cd ..

script:
  - elm-format --validate .
  - elm-test
